# fly.toml app configuration file generated for lu-estilo-api-misty-frost-2101 on 2025-05-26T17:47:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lu-estilo-api-misty-frost-2101'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
