"""add user_id to order_items

Revision ID: 1d00b4be8219
Revises: dd3105fe9167
Create Date: 2025-05-25 04:33:57.121162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d00b4be8219'
down_revision: Union[str, None] = 'dd3105fe9167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'user_id')
    # ### end Alembic commands ###
