"""add phone to client

Revision ID: 84d468d135ce
Revises: ed8254587913
Create Date: 2025-05-26 04:50:03.603103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d468d135ce'
down_revision: Union[str, None] = 'ed8254587913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.String(), nullable=True))
    op.drop_index(op.f('ix_clients_cpf'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_unique_constraint(None, 'clients', ['cpf'])
    op.create_unique_constraint(None, 'clients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_cpf'), 'clients', ['cpf'], unique=True)
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###
