"""ajuste relacionamento orders e clients

Revision ID: 8ab44d78a50e
Revises: 0486ccc63586
Create Date: 2025-05-26 07:37:23.341559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab44d78a50e'
down_revision: Union[str, None] = '0486ccc63586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###
