"""ajuste relacionamento orders e clients

Revision ID: ded59f14cff6
Revises: 8ab44d78a50e
Create Date: 2025-05-26 07:40:19.223758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded59f14cff6'
down_revision: Union[str, None] = '8ab44d78a50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'client_id')
    # ### end Alembic commands ###
