"""ajuste relacionamento orders e clients

Revision ID: e063737b9948
Revises: ded59f14cff6
Create Date: 2025-05-26 07:42:38.379075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e063737b9948'
down_revision: Union[str, None] = 'ded59f14cff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_client_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_client_id_fkey'), 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
